# Site settings
title: Paper Fu
description: Paper's blog

# Profile info
email: fujunchao@supeq.com
site_name: PaperDragons
github_url: https://github.com/paperdragons
github_username: paperdragons

# Build settings
markdown: kramdown

paginate: 5
paginate_path: page:num
gems: [jekyll-paginate]

#highlighter: pygments
#highlighter: rouge

host: 192.168.0.28
